# Generated by Django 4.2.27 on 2025-12-08 12:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリー名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='カラーコード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='金額')),
                ('description', models.TextField(verbose_name='説明')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('credit_card', 'クレジットカード'), ('debit_card', 'デビットカード'), ('electronic_money', '電子マネー'), ('bank_transfer', '銀行振込'), ('other', 'その他')], default='cash', max_length=20, verbose_name='支払い方法')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='api.category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '経費',
                'verbose_name_plural': '経費',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='api_expense_date_890d8d_idx'), models.Index(fields=['category'], name='api_expense_categor_abfaf9_idx')],
            },
        ),
    ]
