# Generated by Django 4.2.27 on 2025-12-08 13:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('file_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ファイルサイズ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='api.expense', verbose_name='経費')),
            ],
            options={
                'verbose_name': '領収書',
                'verbose_name_plural': '領収書',
                'ordering': ['-created_at'],
            },
        ),
    ]
