# Generated by Django 4.2.27 on 2025-12-08 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='支払い方法名')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='コード')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='アイコン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '支払い方法',
                'verbose_name_plural': '支払い方法',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['name'], name='api_payment_name_729235_idx'), models.Index(fields=['is_active'], name='api_payment_is_acti_4629ce_idx')],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='api.paymentmethod', verbose_name='支払い方法'),
        ),
    ]
